// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOZxkgD0owdnnzv6410ZrlRmHiRAIFWfI',
    appId: '1:588558685718:web:7cbccd50fcdc2627264737',
    messagingSenderId: '588558685718',
    projectId: 'noidung3-th2',
    authDomain: 'noidung3-th2.firebaseapp.com',
    storageBucket: 'noidung3-th2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAug67Vo1A7r-LdILRyV9UllBvD2MDNqhw',
    appId: '1:588558685718:android:9ceac1e34fcc2f0e264737',
    messagingSenderId: '588558685718',
    projectId: 'noidung3-th2',
    storageBucket: 'noidung3-th2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgvPsT3TSnAUSoZpMBZPQ_XOMV_OJSFU',
    appId: '1:588558685718:ios:d0613817704768a3264737',
    messagingSenderId: '588558685718',
    projectId: 'noidung3-th2',
    storageBucket: 'noidung3-th2.firebasestorage.app',
    iosBundleId: 'com.example.noidung3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgvPsT3TSnAUSoZpMBZPQ_XOMV_OJSFU',
    appId: '1:588558685718:ios:d0613817704768a3264737',
    messagingSenderId: '588558685718',
    projectId: 'noidung3-th2',
    storageBucket: 'noidung3-th2.firebasestorage.app',
    iosBundleId: 'com.example.noidung3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOZxkgD0owdnnzv6410ZrlRmHiRAIFWfI',
    appId: '1:588558685718:web:2084f2ebfe581674264737',
    messagingSenderId: '588558685718',
    projectId: 'noidung3-th2',
    authDomain: 'noidung3-th2.firebaseapp.com',
    storageBucket: 'noidung3-th2.firebasestorage.app',
  );
}
